#通常不需要編輯
############################################################
#  	Global properties
#   廣域屬性設定
############################################################

# "handlers" 用來指定以逗號分隔的日誌處理器清單。
# 這些處理器類別會在虛擬機器啟動時載入。
# 請注意，這些類別必須存在於系統類別路徑中。
# 預設只設定 ConsoleHandler，且只會顯示
# INFO 等級以上的訊息。
#handlers= java.util.logging.ConsoleHandler

# 若也要加入 FileHandler，請改用下列設定。
handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler, l1j.server.ErrorLogHandler

# 預設全域日誌等級。
# 此設定決定所有日誌記錄器預設要記錄的事件等級。
# 各個日誌記錄器可以再用自己的專用等級設定
# 覆寫此全域等級。
# 請注意，ConsoleHandler 本身也有獨立的等級設定，
# 用來限制輸出到主控台的訊息。
.level= OFF

############################################################
# 日誌處理器專用屬性。
# 設定各日誌處理器的詳細組態。
############################################################

# 預設檔案輸出位置為使用者的家目錄。
java.util.logging.FileHandler.pattern = log/java%u.log
java.util.logging.FileHandler.limit = 500000
java.util.logging.FileHandler.count = 5
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
# java.util.logging.FileHandler.level = FINEST
java.util.logging.FileHandler.level = INFO

# 主控台只輸出 INFO 等級以上的訊息。
# java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = l1j.server.server.ConsoleLogFormatter

# 記錄錯誤（例外）
l1j.server.ErrorLogHandler.pattern = log/error%u.log
l1j.server.ErrorLogHandler.count = 5
l1j.server.ErrorLogHandler.formatter = java.util.logging.SimpleFormatter
l1j.server.ErrorLogHandler.filter = l1j.server.ErrorFiler
l1j.server.ErrorLogHandler.level = WARNING

############################################################
# 各日誌記錄器專用屬性。
# 提供每個日誌記錄器的額外控制設定。
############################################################

# 例如，將 com.xyz.foo 日誌記錄器設定為只記錄 SEVERE
# 等級的訊息：
# l1j.server.level = FINEST
l1j.server.level = FINE
